### ISSUE TITLE
Can I change spaces to tabs?

### ISSUE THREAD

**Issue by h0x91b** [joaojeronimo/node_redis_cluster#7]
In all our projects we use tabs, can I change this project too? (this is BIG commit :) )

**Comment by tleef** [comment]
For what its worth, I'm fairly opposed to tabs particularly in project that are on Github because they use a tab-size of 8.  I am in favor of a .editorconfig however :)

There is a long standing issue open about this here:
https://github.com/isaacs/github/issues/170

example:
https://github.com/tleef/tab-test/blob/master/index.js
